using System.Text;
using JetBrains.Annotations;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using NUnit.Framework;
using Plugboard.Endpoints.Generator;

namespace Plugboard.Endpoints.Tests;

[TestFixture]
internal sealed class EndpointGeneratorTests
{
    private const string HealthEndpoint = """

        namespace TestProject.Features.Health
        {
            using Plugboard;
            using Microsoft.AspNetCore.Routing;

            [Endpoint]
            public static class HealthEndpoint
            {
                public static void MapEndpoint(IEndpointRouteBuilder app) { }
            }
        }
        """;

    private const string TodoGroupWithEndpoint = """

        namespace TestProject.Features.Todos
        {
            using Plugboard;
            using Microsoft.AspNetCore.Routing;

            [EndpointGroup]
            public static class TodoGroup
            {
                public static void Configure(RouteGroupBuilder group) { }
            }

            [Endpoint(typeof(TodoGroup))]
            public sealed class GetTodoEndpoint
            {
                public static void MapEndpoint(IEndpointRouteBuilder app) { }
            }
        }
        """;

    [Test]
    public Task Generate_WithStandaloneEndpoint_ShouldEmitRegistration() =>
        Generate(HealthEndpoint, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace TestAssembly;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    global::TestProject.Features.Health.HealthEndpoint.MapEndpoint(app);
                    return app;
                }
            }
            """);

    [Test]
    public Task Generate_WithGroupedEndpoint_ShouldEmitGroupRegistration() =>
        Generate(TodoGroupWithEndpoint, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace TestAssembly;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    app.RegisterTodoGroup();
                    return app;
                }

                /// <summary>Maps <see cref="global::TestProject.Features.Todos.TodoGroup"/> and the endpoints declared for it.</summary>
                internal static IEndpointRouteBuilder RegisterTodoGroup(this IEndpointRouteBuilder app)
                {
                    RouteGroupBuilder group = app.MapGroup(string.Empty);
                    global::TestProject.Features.Todos.TodoGroup.Configure(group);
                    global::TestProject.Features.Todos.GetTodoEndpoint.MapEndpoint(group);
                    return app;
                }
            }
            """);

    [Test]
    public Task Generate_WithGroupWithoutEndpoints_ShouldStillRegisterGroup()
    {
        const string source = """

            namespace TestProject.Features.Admin
            {
                using Plugboard;
                using Microsoft.AspNetCore.Routing;

                [EndpointGroup]
                public static class AdminGroup
                {
                    public static void Configure(RouteGroupBuilder group) { }
                }
            }
            """;

        return Generate(source, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace TestAssembly;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    app.RegisterAdminGroup();
                    return app;
                }

                /// <summary>Maps <see cref="global::TestProject.Features.Admin.AdminGroup"/> and the endpoints declared for it.</summary>
                internal static IEndpointRouteBuilder RegisterAdminGroup(this IEndpointRouteBuilder app)
                {
                    RouteGroupBuilder group = app.MapGroup(string.Empty);
                    global::TestProject.Features.Admin.AdminGroup.Configure(group);
                    return app;
                }
            }
            """);
    }

    [Test]
    public Task Generate_WithBothKinds_ShouldEmitAll() =>
        Generate(HealthEndpoint + TodoGroupWithEndpoint, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace TestAssembly;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    global::TestProject.Features.Health.HealthEndpoint.MapEndpoint(app);
                    app.RegisterTodoGroup();
                    return app;
                }

                /// <summary>Maps <see cref="global::TestProject.Features.Todos.TodoGroup"/> and the endpoints declared for it.</summary>
                internal static IEndpointRouteBuilder RegisterTodoGroup(this IEndpointRouteBuilder app)
                {
                    RouteGroupBuilder group = app.MapGroup(string.Empty);
                    global::TestProject.Features.Todos.TodoGroup.Configure(group);
                    global::TestProject.Features.Todos.GetTodoEndpoint.MapEndpoint(group);
                    return app;
                }
            }
            """);

    [Test]
    public Task Generate_WithRecordAndStructEndpoints_ShouldEmitRegistration()
    {
        const string source = """

            namespace TestProject.Features.Misc
            {
                using Plugboard;
                using Microsoft.AspNetCore.Routing;

                [Endpoint]
                public sealed record RecordEndpoint
                {
                    public static void MapEndpoint(IEndpointRouteBuilder app) { }
                }

                [Endpoint]
                public readonly struct StructEndpoint
                {
                    public static void MapEndpoint(IEndpointRouteBuilder app) { }
                }
            }
            """;

        return Generate(source, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace TestAssembly;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    global::TestProject.Features.Misc.RecordEndpoint.MapEndpoint(app);
                    global::TestProject.Features.Misc.StructEndpoint.MapEndpoint(app);
                    return app;
                }
            }
            """);
    }

    [Test]
    public Task Generate_WithDuplicateGroupNames_ShouldSkipCollidingGroups()
    {
        const string source = TodoGroupWithEndpoint + """

            namespace TestProject.Features.Other
            {
                using Plugboard;
                using Microsoft.AspNetCore.Routing;

                [EndpointGroup]
                public static class TodoGroup
                {
                    public static void Configure(RouteGroupBuilder group) { }
                }
            }
            """ + HealthEndpoint;

        return Generate(source, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace TestAssembly;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    global::TestProject.Features.Health.HealthEndpoint.MapEndpoint(app);
                    return app;
                }
            }
            """);
    }

    [Test]
    public Task Generate_WithEndpointMissingMapEndpoint_ShouldEmitNothing() => Generate("""

        namespace TestProject
        {
            using Plugboard;

            [Endpoint]
            public static class BrokenEndpoint { }
        }
        """);

    [Test]
    public Task Generate_WithEndpointPointingToUnmarkedGroup_ShouldEmitNothing() => Generate("""

        namespace TestProject
        {
            using Plugboard;
            using Microsoft.AspNetCore.Routing;

            public static class NotAGroup
            {
                public static void Configure(RouteGroupBuilder group) { }
            }

            [Endpoint(typeof(NotAGroup))]
            public static class OrphanEndpoint
            {
                public static void MapEndpoint(IEndpointRouteBuilder app) { }
            }
        }
        """);

    [Test]
    public Task Generate_WithNoEndpoints_ShouldEmitNothing() => Generate("""

        namespace TestProject
        {
            public class SomeClass { }
        }
        """);

    [Test]
    public Task Generate_WithRootNamespaceProperty_ShouldEmitIntoRootNamespace() =>
        Generate(HealthEndpoint, """
            // <auto-generated/>
            #nullable enable

            using Microsoft.AspNetCore.Builder;
            using Microsoft.AspNetCore.Routing;

            namespace My.Custom.Root;

            internal static class EndpointRegistrationExtensions
            {
                /// <summary>Maps every endpoint and endpoint group declared in this assembly.</summary>
                internal static IEndpointRouteBuilder RegisterEndpoints(this IEndpointRouteBuilder app)
                {
                    global::TestProject.Features.Health.HealthEndpoint.MapEndpoint(app);
                    return app;
                }
            }
            """, rootNamespace: "My.Custom.Root");

    [AssertionMethod]
    private static Task Generate(string source, string? expected = null, string rootNamespace = "TestAssembly")
    {
        var test = new CSharpSourceGeneratorTest<EndpointGenerator, DefaultVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = TestReferences.Net80AspNetCore
        };
        test.TestState.AdditionalReferences.Add(typeof(EndpointAttribute).Assembly);

        // build_property.* values reach the generator through a global analyzer config, exactly as MSBuild passes them.
        test.TestState.AnalyzerConfigFiles.Add(("/.globalconfig", $"""
            is_global = true
            build_property.RootNamespace = {rootNamespace}
            """));

        // No expected text means the generator must emit nothing; the framework asserts the exact set of generated files.
        if (expected is not null)
        {
            test.TestState.GeneratedSources.Add((typeof(EndpointGenerator), "EndpointRegistration.g.cs",
                SourceText.From(expected.ReplaceLineEndings("\n"), Encoding.UTF8)));
        }

        return test.RunAsync();
    }
}
