<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Plugboard.Endpoints.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <EnableNUnitRunner>true</EnableNUnitRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Plugboard.Endpoints\Plugboard.Endpoints.csproj" />
        <ProjectReference Include="..\..\src\Plugboard.Endpoints.Generator\Plugboard.Endpoints.Generator.csproj" />
    </ItemGroup>

</Project>
